name: nftools
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rinf: ^6.15.0
  get: ^4.6.6
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  cupertino_icons: ^1.0.8
  easy_debounce: ^2.0.3
  flex_color_scheme: ^7.3.1
  fluentui_system_icons: ^1.1.260
  fluent_ui: ^4.9.2
  go_router: ^14.3.0
  graphic: ^2.5.0
  intl: ^0.19.0
  window_manager: ^0.4.3
  tray_manager: ^0.2.4
  data_table_2: ^2.5.15
  file_picker: ^8.1.4
  flutter_markdown: ^0.7.4+3
  markdown_widget: ^2.3.2+6
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.16
  meta: ^1.15.0
  pretty_diff_text: ^2.0.0
  re_editor: ^0.7.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/fonts/
  fonts:
    - family: oppo_sans
      fonts:
        - asset: assets/fonts/OPPOSans-Regular.ttf