name: nftools
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rinf: ^8.6.0
  get: ^4.6.6
  fixnum: ^1.1.0
  cupertino_icons: ^1.0.8
  easy_debounce: ^2.0.3
  flex_color_scheme: ^8.2.0
  fluentui_system_icons: ^1.1.273
  fluent_ui: ^4.11.3
  go_router: ^15.1.2
  graphic: ^2.5.0
  intl: 0.20.2
  window_manager: ^0.4.3
  tray_manager: 0.5.0
  file_picker: ^10.1.9
  flutter_markdown: ^0.7.4+3
  markdown_widget: ^2.3.2+6
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.16
  meta: ^1.16.0
  pretty_diff_text: ^2.0.0
  re_editor:
    git:
      url: https://github.moeyy.xyz/https://github.com/copywith99/re-editor.git
      ref: d448e01d8ff25081209d1ac7d1058503251670f6
  pasteboard: ^0.4.0
  re_highlight: ^0.0.3
  tuple: ^2.0.2
  # ========= video support ========
  # video_player_media_kit: ^1.0.5
  # media_kit_libs_windows_video: any
  # media_kit_libs_linux: any
  # media_kit: ^1.2.0
  # media_kit_video: ^1.3.0
  # ========= video support end ========
  logger: ^2.5.0
  list_ext: ^1.0.6
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_shaders: ^0.1.3
  keymap: ^0.0.5
  dio: ^5.9.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/fonts/
  shaders:
    - assets/shaders/wrap.frag
  fonts:
    - family: oppo_sans
      fonts:
        - asset: assets/fonts/OPPOSans-Regular.ttf